### ISSUE TITLE
/hm/static 主机信息缺了OS内核版本信息

### ISSUE THREAD

**Issue by jiejiecn** [jkstack/smartagent-server#3]
![hm_static](https://user-images.githubusercontent.com/11746870/169081634-48f7bd97-1f47-4e5c-bda1-d84fc2f14ca3.PNG)

**Comment by lwch** [comment]
问题出在server的返回值上不在这里

**Comment by jiejiecn** [comment]
用户怎么知道，插件在哪里提issue呢？

**Comment by lwch** [comment]
返回数据缺少字段统一属于server的问题，返回数据不正确可以先放到server

**Comment by lwch** [comment]
fixed: #4
