### ISSUE TITLE
Server 增加docker相关操作接口

### ISSUE THREAD

**Issue by jiejiecn** [jkstack/smartagent-server#6]
server端新增接口下发docker相关操作接口

1. 获取主机运行容器信息列表： docker ps -a 信息

2. 获取主机已有容器镜像列表： docker images 信息

3. 运行指定镜像：			
- 支持从指定私有registry拉取并运行
- 支持用户传递高级配置参数，如：端口映射、目录映射、CPU limit，RAM limit等

4. 终止指定容器：	             根据 containerid，name 两个条件二选一

5. 重启、暂停指定容器：     根据 containerid，name 两个条件二选一

**Comment by lwch** [comment]
你牛逼你自己做
